### ISSUE TITLE
ReaderSdk.initialize breaks definition of platform brightness (aka light or dark theme)

### ISSUE THREAD

**Issue by TatsuUkraine** [square/reader-sdk-flutter-plugin#88] opened 2022-07-12 22:12 UTC
### Describe the issue
Starting from Flutter 3, after ReaderSdk.initialize is invoked, App fails into light theme even if Dark theme is enabled in the system, settings

### To Reproduce

  1. Follow the instructions in doc
  2. Ensure that Material Theme has `ThemeMode.system`
  3. Start the app with Dark theme enabled in the system settings

### Expected behavior
App uses Dark theme

**Environment (please complete the following information):**

  - platform: Android
  - OS and version: 12
  - dev environment: MacOS
  - Reader SDK version: >=1.5.6

### Additional context
All works fine with Flutter 2.x. Issue appears only on Android 12 and only if app built with Flutter 3.x
Removing `ReaderSdk.initialize` from `onCreate` method in Application fixes the issue

**Comment by CharmisG** [comment] 2022-07-13 10:24
@TatsuUkraine 
Actually It is plugin only we haven't code for dark mode yet.
but we definitely ping you when we implement dark mode.

**Comment by TatsuUkraine** [comment] 2022-07-13 10:28
@CharmisG also, the issue not in reader sdk intents, issue that after intialize method is invoked flutter portion starts receiving light theme through the platform channel

**Comment by CharmisG** [comment] 2022-08-03 06:55
@TatsuUkraine 
It was a permission issue above android version 12 so need to give Bluetooth and location permission in plugin of the android folder
so feel free to reopen this issue if you are still facing this issue.
Thank you !!

**Comment by TatsuUkraine** [comment] 2022-08-03 07:13
@CharmisG I don't have access to reopen the issue! I already tried a variant with requesting Bluetooth permissions before initialize it didn't help.

What specific location permissions should be granted before initialize method is invoked to fix this issue?

**Comment by CharmisG** [comment] 2022-08-03 07:15
@TatsuUkraine 
Permission to give in android manifest :

<uses-permission
        android:name="android.permission.BLUETOOTH"
        android:maxSdkVersion="30" />
    <uses-permission
        android:name="android.permission.BLUETOOTH_ADMIN"
        android:maxSdkVersion="30" />
    
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />

    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

**Comment by TatsuUkraine** [comment] 2022-08-03 07:27
@CharmisG it doesn't solve the issue, it solves problems with crash on app start, but not with Theme

**Comment by CharmisG** [comment] 2022-08-03 08:48
@TatsuUkraine 

Please check below code and add permission in main android manifest and example -> android -> manifest

![Screenshot 2022-08-03 at 2 15 13 PM](https://user-images.githubusercontent.com/102352276/182565396-134ecbdf-e3b1-44ae-8aa5-217caa75f98a.png)

![Screenshot 2022-08-03 at 2 18 37 PM](https://user-images.githubusercontent.com/102352276/182566081-7ea89747-ce92-411e-8842-ba11c10f910c.png)

**Comment by TatsuUkraine** [comment] 2022-08-03 09:05
@CharmisG still doesn't solve the issue

AndroidManifest.xml
```xml
    <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />

    <!-- Needed to communicate with already-paired Bluetooth devices. (Android 12 upwards)-->
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADVERTISE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```

MainActivity.kt
```kt
class MainActivity: FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            val sdkPermissions: Array<String> = arrayOf(Manifest.permission.BLUETOOTH_CONNECT, Manifest.permission.BLUETOOTH_SCAN, Manifest.permission.BLUETOOTH_ADVERTISE, Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION)

            if (sdkPermissions.all { checkSelfPermission(it) == PackageManager.PERMISSION_GRANTED }) {
                ReaderSdk.initialize(application)
                Toast.makeText(this, "Reader SDK initialized", Toast.LENGTH_SHORT).show()
            } else {
                ActivityCompat.requestPermissions(this, sdkPermissions, READER_SDK_PERMISSIONS_CODE)
            }
        } else {
            ReaderSdk.initialize(application)
            Toast.makeText(this, "Reader SDK initialized", Toast.LENGTH_SHORT).show()
        }
    }

    override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<out String>, grantResults: IntArray) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        if (requestCode == READER_SDK_PERMISSIONS_CODE && grantResults.all { it == PackageManager.PERMISSION_GRANTED }) {
            ReaderSdk.initialize(application)
            Toast.makeText(this, "Reader SDK initialized", Toast.LENGTH_SHORT).show()
            return
        }

        Toast.makeText(this, "Reader SDK not initialized", Toast.LENGTH_SHORT).show()
    }

    companion object {
        private const val READER_SDK_PERMISSIONS_CODE = 100
    }
}
```

**Comment by TatsuUkraine** [comment] 2022-08-03 09:11
p.s. example project in plugin repo doesn't work with flutter 3

```
e: /Users/tatsu/.pub-cache/hosted/pub.dartlang.org/barcode_scan-2.0.2/android/src/main/kotlin/de/mintware/barcode_scan/BarcodeScanPlugin.kt: (19, 1): Class 'BarcodeScanPlugin' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: /Users/tatsu/.pub-cache/hosted/pub.dartlang.org/barcode_scan-2.0.2/android/src/main/kotlin/de/mintware/barcode_scan/BarcodeScanPlugin.kt: (57, 9): Smart cast to 'Activity' is impossible, because 'registrar.activity()' is a complex expression
e: /.pub-cache/hosted/pub.dartlang.org/barcode_scan-2.0.2/android/src/main/kotlin/de/mintware/barcode_scan/BarcodeScanPlugin.kt: (67, 36): Type mismatch: inferred type is String? but String was expected
e: /.pub-cache/hosted/pub.dartlang.org/barcode_scan-2.0.2/android/src/main/kotlin/de/mintware/barcode_scan/BarcodeScanPlugin.kt: (76, 47): Type mismatch: inferred type is Activity? but Context was expected
e: /.pub-cache/hosted/pub.dartlang.org/barcode_scan-2.0.2/android/src/main/kotlin/de/mintware/barcode_scan/BarcodeScanPlugin.kt: (81, 43): Type mismatch: inferred type is Activity? but Activity was expected
e: /.pub-cache/hosted/pub.dartlang.org/barcode_scan-2.0.2/android/src/main/kotlin/de/mintware/barcode_scan/BarcodeScanPlugin.kt: (85, 5): 'onRequestPermissionsResult' overrides nothing
```

**Comment by TatsuUkraine** [comment] 2022-08-03 09:13
if you building the app with flutter 2, there are NO issue with theme (I pointed out this in the issue description)

**Comment by CharmisG** [comment] 2022-08-04 04:14
@TatsuUkraine 
Sorry for the trouble but I'm also figuring out an issue from my side now I have kept all required permission for android 12 on flutter 3 so can you please check the latest code and let me know the status?

**Comment by TatsuUkraine** [comment] 2022-08-04 08:49
@CharmisG if to follow `getting started` docs with the most recent changes it doesn't solve anything, app still crashes during the start. Also not quite sure if any of the recent changes can solve issue described here

**Comment by CharmisG** [comment] 2022-08-16 06:43
@TatsuUkraine 
Sorry for the delay but I'm working on it and I'll update you soon.
Thank you !!

**Comment by CharmisG** [comment] 2022-08-25 07:01
@TatsuUkraine 
Sorry for the delay but we are using the permission_handler plugin and this plugin itself has this permission error that's why it's crashing so we are waiting for this(permission_handler) plugin update and we are continuously touched with this plugin and I'll let you know when we get any response and will update you!

Plugin link: https://pub.dev/packages/permission_handler

Thank you !!

**Comment by TatsuUkraine** [comment] 2022-08-25 07:04
@CharmisG I'm not sure what you mean. App doesn't crashes , theme doesn't work properly (please read ticket description)

**Comment by TatsuUkraine** [comment] 2022-08-25 07:08
@CharmisG also, this plugin doesn't use permission handler plugin

**Comment by CharmisG** [comment] 2022-08-25 07:14
@TatsuUkraine 
Can you please share video?
How your app is behaving in flutter 3

**Comment by TatsuUkraine** [comment] 2022-08-25 12:08
@CharmisG not sure that I'm following what kind of video you need to see? flutter always chooses a light theme even when ThemeMode is `system` and the dark mode is enabled on the Android device

**Comment by CharmisG** [comment] 2022-09-01 07:15
@TatsuUkraine 
 PR is merged please check in the latest code.
 Thank you foe help !!!

**Comment by TatsuUkraine** [comment] 2022-09-01 07:16
@CharmisG it's not how it works! you need to publish the most recent version to pub.dev to make it available for everyone!

**Comment by TatsuUkraine** [comment] 2022-09-01 07:17
also, these changes doesn't solve this issue, please repopen the PR!

**Comment by TatsuUkraine** [comment] 2022-09-01 07:18
@hukid

**Comment by hukid** [comment] 2022-09-01 17:59
@TatsuUkraine We'll publish the new plugin soon. Thanks a lot, @TatsuUkraine!

**Comment by TatsuUkraine** [comment] 2022-09-01 18:04
@hukid I tried all this updates already, and issue described on this ticket is not solved by these changes

**Comment by hukid** [comment] 2022-09-01 18:32
@TatsuUkraine, re-opened this issue.

**Comment by hukid** [comment] 2022-09-01 18:33
@TatsuUkraine while we are investigating, if you see a fix, feel free to send the PR.

**Comment by TatsuUkraine** [comment] 2022-09-01 18:39
@hukid I tried to find a reason, but no luck so far(( I started to think that it may be somewhere deep in Android Reader SDK, where I don't have access(

**Comment by hukid** [comment] 2022-09-01 21:54
I actually feel this is a bug in Flutter 3 given the issues doesn't exist in Flutter 2.

**Comment by TatsuUkraine** [comment] 2022-09-01 22:07
@hukid could be, but I'm not quite sure since native layer starts sending wrong theme only after ReaderSdk.intialize method is invoked and on androids 12 and 13. On 11 all works fine

**Comment by TatsuUkraine** [comment] 2022-09-01 22:11
Also, once initialize method is invoked, each next time app starts from the scratch (from killed state) , even native splash screen thinks that app uses light theme, nevertheless it always relying on system settings. I can assume it happens because reader sdk has own background process

**Comment by TatsuUkraine** [comment] 2022-09-01 22:12
But again, I don't have access to sources of the reader sdk to confirm that this happens because of it

**Comment by hukid** [comment] 2022-09-02 16:07
I will bring it to Reader SDK Android team and check if there is any solution.

**Comment by TatsuUkraine** [comment] 2022-09-02 16:55
Thank you

**Comment by TatsuUkraine** [comment] 2022-09-18 14:13
@hukid is there any update regarding this issue? Do you need any additional information or code to help this get fixed?

**Comment by shauna-kimura** [comment] 2022-09-19 17:46
Hi @TatsuUkraine! I'm from the Reader SDK Android team. At this time, dark mode is not supported. Following the release of Android 12, SPOS implemented a change to prevent dark mode from being enabled due to flickering issues on Samsung devices that was causing poor user experiences. We’re constantly working to improve our features based on feedback like this, so I’ll be sure to share your request to the API product team.

**Comment by TatsuUkraine** [comment] 2022-09-19 17:53
@shauna-kimura thanks for reply. Is there any way to avoid disabling dark theme globally for the app and keep it only for intent/activity that launched when checkout process started?

**Comment by shauna-kimura** [comment] 2022-09-26 20:49
Keeping in mind that we don't support it, I found [this link](https://www.digitalocean.com/community/tutorials/android-daynight-theme-night-mode) that may be helpful. Another option could be to try [UiModeManager](https://developer.android.com/reference/android/app/UiModeManager#setApplicationNightMode(int)) to set the theme for your app globally and then temporarily disable dark mode when opening RSDK screens. I would suggest doing a check for the build version prior to enabling dark mode to prevent the flickering issue on Samsung devices that might occur (e.g. `if (Build.VERSION.SDK_INT >= 31)`).

**Comment by TatsuUkraine** [comment] 2022-09-26 22:42
@shauna-kimura thank you for links, I will take a look. But I'm not sure that I'm following, entire app forced to use dark theme after ReaderSdk.intialize method is invoked. Before this method is used - app uses system settings to define the theme mode. How manually switching theme solves the fact that intialize method switches the app to the light theme?

**Comment by TatsuUkraine** [comment] 2022-10-18 06:11
@CharmisG why this ticket was closed? I still waiting for the answer on my question, also this issue still exist, noone fixed it yet

**Comment by Aakashp02** [comment] 2023-04-03 09:19
Hello,

Got any solution for this? because i am facing error in flutter android

**Comment by TatsuUkraine** [comment] 2023-04-03 09:33
@Aakashp02 I do. We just published release, will see how it goes, not sure that it's a proper fix though. Going to watch on error reports and if all good, will propose changes for this package

https://github.com/TatsuUkraine/reader-sdk-flutter-plugin/compare/master...TatsuUkraine:reader-sdk-flutter-plugin:flutter-theme-fix?expand=1#diff-e62dc41d5752d7a035cf8fc089d566380a737c4f49b8b6e37f8228fa8e55c421R168

**Comment by Aakashp02** [comment] 2023-04-03 09:47
Thank you @TatsuUkraine . let me check your branch

**Comment by Aakashp02** [comment] 2023-04-03 10:17
Still i am getting below error:

E/MethodChannel#square_reader_sdk(23609): Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
D/EGL_emulation(23609): app_time_stats: avg=38.11ms min=2.85ms max=659.30ms count=35
E/flutter (23609): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (23609): Receiver: null
E/flutter (23609): Tried calling: []("debugCode")
E/flutter (23609): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (23609): #1      ReaderSdk.isAuthorized
reader_sdk.dart:35
E/flutter (23609): <asynchronous suspension>
E/flutter (23609): #2      _ButtonContainerState.checkPermissionsAndNavigate

**Comment by TatsuUkraine** [comment] 2023-04-03 10:22
It probably not related to theme issue. What sdk version are you using?

**Comment by Aakashp02** [comment] 2023-04-03 10:23
i am using latest one

**Comment by Aakashp02** [comment] 2023-04-03 10:24
example is working fine but when i download dependency and set all things as per given in doc its giving me error which i sent. almost 3 days i spent on it but not getting nay solution. its happening in android only. in ios its working fine.

**Comment by fka3** [comment] 2023-04-04 20:51
Re-closing; we said already that it's not supported.

Specifically, the Reader SDK Activities don't support it; if you insist on trying, what I would suggest is that you look at the merged `AndroidManifest.xml` of your application, and see whether you can work with `tools:replace` or the like to adapt that outcome... but Square isn't going to help, or provide support to, that effort.  (The issue is that Square Point-of-Sale is what actually has that code, and _that_ doesn't want to support dark mode.)

**Closed by fka3** 2023-04-04 20:51 UTC
Labels: bug

**Comment by TatsuUkraine** [comment] 2023-04-04 21:04
@fka3 I'm not asking to support dark mode, I'm asking to don't break flutter theme definition)
